spring:
  profiles:
    active: dev


---
spring:
    profiles: dev
    application:
      name: microservercloud-config-hfming-dev

---
spring:
  profiles: test
  application:
    name: microservercloud-config-hfming-test
