spring:
  profiles:
    active: dev
---

server:
  port: 3355

spring:
  profiles: dev
  application:
    name: microsericecloud-config-client

#服务注册到eureka地址
eureka:
  client: #客户端注册进eureka服务列表内
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: microservicecloud-config-client  # 自定义 Eureka 实例名称
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: microservicecloud
  company.name: www.hfming.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 3355

spring:
  profiles: test
  application:
    name: microsericecloud-config-client

#服务注册到eureka地址
eureka:
  client: #客户端注册进eureka服务列表内
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: microservicecloud-config-client  # 自定义 Eureka 实例名称
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: microservicecloud
  company.name: www.hfming.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$