spring:
  profiles:
    active: dev
---

server:
  port: 8201

spring:
  profiles: dev
  application:
    name: microsericecloud-config-client

#服务注册到eureka地址
eureka:
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: microservicecloud-config-client  # 自定义 Eureka 实例名称
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: microservicecloud
  company.name: www.hfming.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8202

spring:
  profiles: test
  application:
    name: microsericecloud-config-client

#服务注册到eureka地址
eureka:
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: microservicecloud-config-client  # 自定义 Eureka 实例名称
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: microservicecloud
  company.name: www.hfming.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$